/*
A layout is UI that is shared between multiple pages. On navigation, layouts preserve state, remain interactive, and do not rerender.
*/

import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import styles
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

//metadata of page
export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {/* For every page it provides layout */}
        
        {/* creating a Appbar */}
        {/* border-b: its for creating bottom border */}
        
        {/* Dynamic content: The children prop will be replaced by the 
          content from the individual pages. */}
        <div className="p-5 border-b">
          Medium
        </div>
        <p className = "text-center">
        Hi there from ROOT layout / GLOBAL layout !!!
        A layout is UI that is shared between multiple pages. On navigation, layouts preserve state, remain interactive, and do not rerender
        </p>
        
    
        {children}
      </body>
       
    </html>
  );
}
